### ISSUE TITLE
可否在 release 下新增所有字体文件的打包文档?

### ISSUE THREAD

**Issue by singularitti** [lxgw/LxgwBright#1]
理由同[这里](https://github.com/lxgw/LxgwWenKai/issues/54#issuecomment-1037523305)，方便我把这款字体推到 macOS 的包管理器上。看到您还有其他字体 repo，我就不一个一个开 issue 了，希望也能一起打包一下。

**Comment by lxgw** [comment]
这个项目的 release 里面 source code (tar.gz) 不是打包的文档吗？

**Comment by singularitti** [comment]
哦哦，我的意思是打包的二进制文档，不是源代码的。比如 TTF 的打包，因为 Homebrew cask 是直接下载二进制文件的。这里确实是直接给了二进制文件，但是其他字体（比如 [霞鹜文楷](https://github.com/lxgw/LxgwWenKai)）好像只给了源代码。这个 issue 开错 repo 了。
