### ISSUE TITLE
很喜欢LXGW中文字体，能缝合一个等宽的英文字体吗？谢谢，期待

### ISSUE THREAD

**Issue by iuuunlyk** [lxgw/LxgwBright#10]
很喜欢LXGW中文字体，能缝合一个等宽的英文字体吗？谢谢，期待

**Comment by lxgw** [comment]
本合并字体的中文部分 [霞鹜文楷](https://github.com/lxgw/LxgwWenKai) 自带等宽版。

除此之外不会提供与其他等宽英文字体的等宽版。

**Comment by lxgw** [comment]
[Monaspace Argon](https://github.com/githubnext/monaspace) 如何？

![Image_1726842195532.png](https://github.com/user-attachments/assets/a20b79fb-8369-4d1d-94b4-d9c47323a0ef)
![Image_1726842197269.png](https://github.com/user-attachments/assets/ad80116c-2174-42b6-9fd6-8111e4bcb928)
![Image_1726842198308.png](https://github.com/user-attachments/assets/13aeb5e2-2b29-4137-92d9-d3125b988ff1)
![Image_1726842254784.png](https://github.com/user-attachments/assets/82b6bab7-6d8b-46a5-9ed4-018bcdc36cee)

**Comment by lxgw** [comment]
https://github.com/lxgw/LxgwBright-Code
