### ISSUE TITLE
有个疑惑，为什么现在新字体，跟传统字体的字高不同？

### ISSUE THREAD

**Issue by shanxindou01** [lxgw/LxgwBright#12]
个人本来很喜欢思源黑体，以及衍射出来的各种字体，比如思源宋体、霞鹜文楷、朱雀仿宋等，但我发现自从思源黑体之后出的中文字体，字高都特别高，而且无法通过调节段落间距等方式缩回。而早期的字体（宋体、仿宋、黑体、楷体等）字高都不高。导致每次使用新的字体后排版就变得明显稀疏，非常不习惯。

以下截图为WPS中不同字体的排版情况，字号均为五号，段落间距均为默认的1倍间距。可以看见明显行距不一样。
![2024-10-09_103748](https://github.com/user-attachments/assets/2618a25a-5216-432e-bae5-fbce8fa12d4a)

请问：
1、在WPS（或Word）中如何设置才能达到宋体相同的行间距？
2、若为字高的问题，能否在设计之初就设为与宋体相似的字高？

**Comment by lxgw** [comment]
对于您的这个疑惑，由于古早的简中字体只做 GBK 或者 GB 2312 收录的字，并不考虑超出字框的字符，所以行距就显得窄些；而近年来新出的一些字体除了包含汉字、假名、基本西文之外，还会包含一些其他语种会使用的字，以及更多特殊符号，其中的一些字符高度可能会超出以往中文字体的高度，于是把上行值和下行值适当加大，这样与以往的字体相比行距就高了（当然，我这么解答可能有些不严谨，还是期待专业人士的解答）。

要在 Word 里解决这个问题，请您「右键→段落→定义文档网格时对齐网格」，取消勾选。

**Comment by shanxindou01** [comment]
> 对于您的这个疑惑，由于古早的简中字体只做 GBK 或者 GB 2312 收录的字，并不考虑超出字框的字符，所以行距就显得窄些；而近年来新出的一些字体除了包含汉字、假名、基本西文之外，还会包含一些其他语种会使用的字，以及更多特殊符号，其中的一些字符高度可能会超出以往中文字体的高度，于是把上行值和下行值适当加大，这样与以往的字体相比行距就高了（当然，我这么解答可能有些不严谨，还是期待专业人士的解答）。
> 
> 要在 Word 里解决这个问题，请您「右键→段落→定义文档网格时对齐网格」，取消勾选。

感谢您的回答，这个方法目前看来还不错，谢谢！
另外，还有个问题，能否出一个把那些其它字符剔除掉的版本呢？或者设计得跟汉字一样矮呢？明明汉字是正方形结构的，拉高后都被弄得没法排版了。

**Comment by lxgw** [comment]
> 另外，还有个问题，能否出一个把那些其它字符剔除掉的版本呢？或者设计得跟汉字一样矮呢？明明汉字是正方形结构的，拉高后都被弄得没法排版了。

抱歉，没有这个计划。
