### ISSUE TITLE
LXGWBrightClassic数字0-9高度不一致

### ISSUE THREAD

**Issue by tanqimin** [lxgw/LxgwBright#2]
在Calibre中设置为默认字体为LXGWBrightClassic，发现数字高度显示不一致

**Comment by lxgw** [comment]
建议了解一下 Old-style 数字（[参考链接](https://www.zhihu.com/question/19765436)，类似 Georgia 字体），Classic  版本就是旧字形汉字与 Old-style 数字搭配的。

当然，如果不适应的话后续会换成 Lining 数字的版本（与 LXGW Bright 一样采用 Ysabeau Office 西文字体），字体名也会改为 LXGW Bright TC。

**Comment by lxgw** [comment]
现在三种字形版本的西文部分统一为 Ysabeau Office，不再采用 Ysabeau 的 old-style 数字。
