### ISSUE TITLE
霞鹜文楷与 Ysabeau Office 字型大小差异较大

### ISSUE THREAD

**Issue by aik2mlj** [lxgw/LxgwBright#4]
个人非常喜欢这一款字体！当前所有界面字体都改用为此。
在个人使用中唯一稍感不足的是，霞鹜文楷与 Ysabeau Office 字型大小差异较大，使得同一字号下，拉丁字母明显比汉字拥挤。或许可以增大 Ysabeau Office 的字号。不知作者怎么看？

**Comment by drakeet** [comment]
可以的话，请恕我我投一票反对。现在大小合适，不希望被改变。
