### ISSUE TITLE
请问这个版本的字体是否提供magisk模块

### ISSUE THREAD

**Issue by Mixlining** [lxgw/LxgwBright#5]
感觉这个版本补的西文字体好看,但是很遗憾没找到模块

**Comment by Mixlining** [comment]
貌似网盘删除了

**Comment by lxgw** [comment]
Magisk 模块请在[蓝奏云（密码 4dqt）](https://lxgw.lanzoum.com/b0ct7rg9g) 下载，将在本项目更新后 48 小时内更新。
