### ISSUE TITLE
LXGW Bright GB 中的 U+22EF 字形不符合国标规范

### ISSUE THREAD

**Issue by PumpkinJui** [lxgw/LxgwBright#6]
LXGW Bright GB 中的 “…”(U+22EF) 没有居中显示，不符合[国标规范](http://www.moe.gov.cn/ewebeditor/uploadfile/2015/01/13/20150113091548267.pdf)。可能继承自 Ysabeau Office。
应当改为 霞鹜文楷 GB 那里的样式，如下图。
![……](https://user-images.githubusercontent.com/76104432/207507501-287646be-191d-41e3-bc08-e7f50fb5ae1c.png)
国标中的省略号形式定义如下图。
![国标中的形式定义](https://user-images.githubusercontent.com/76104432/207509548-8e0ae950-978d-4440-8a97-5bebc6ba2faa.png)

(为了方便称呼我没有特别区分 “省略号”(……) 和 “…”，见谅。)

**Comment by lxgw** [comment]
请注意这里的 GB 仅是指汉字是 GB 风格，而省略号是直接使用西文的字体。
