### ISSUE TITLE
希望能够有等宽字体版本

### ISSUE THREAD

**Issue by rexzhang** [lxgw/LxgwBright#7]
RT

**Comment by lxgw** [comment]
那么您觉得等宽版搭配什么字体，能给点建议吗？

**Comment by lxgw** [comment]
那么您觉得应该搭配什么等宽西文字体（类似 Ysabeau 这种风格能跟文楷的风格相搭配的）更合适，能给点建议吗？

**Comment by rexzhang** [comment]
我个人日常用得多的是 Monaco, 不过这个属于个人喜好.如果要做选择的话,可能可以考虑如下几点:
- 风格匹配
- 授权友好
- 适合编程(个人认为楷体适合做文字工作,宋体适合阅读)
- 字体在相对低分辨率/显示尺寸较小时表现依然比较好的

另外,建议在发布时能同时提供 `.ttc` 文件,这个对分发和推广更有利,分体文件更适合开发者用来整合进软件

**Comment by rexzhang** [comment]
补充一下,我主要是期望这个字体用于 markdown 笔记的环境,编程环境其实对中文的等宽需求实际上是不存在的(理论上有,比如要发展中文编程,以及有大量中文文本的代码环境)

**Comment by rexzhang** [comment]
今天刚刚开始尝试用 `霞鹜文楷等宽 Light` 在 Joplin 中使用, 等宽效果不错, 但总感觉差那么一点点

**Comment by rexzhang** [comment]
刚刚又将 `LXGWBright-Regular` 应用到 Joplin 中认真对比了下, 应该就是当前 `霞鹜文楷等宽 Light` 中的西文字体与中文字体不协调导致的问题, `LXGWBright-Regular` 看着久很舒服了. `Ysabeau` 这个字体风格不错

**Comment by lxgw** [comment]
[Monaspace Argon](https://github.com/githubnext/monaspace) 如何？

![Image_1726842195532.png](https://github.com/user-attachments/assets/a20b79fb-8369-4d1d-94b4-d9c47323a0ef)
![Image_1726842197269.png](https://github.com/user-attachments/assets/ad80116c-2174-42b6-9fd6-8111e4bcb928)
![Image_1726842198308.png](https://github.com/user-attachments/assets/13aeb5e2-2b29-4137-92d9-d3125b988ff1)
![Image_1726842254784.png](https://github.com/user-attachments/assets/82b6bab7-6d8b-46a5-9ed4-018bcdc36cee)

**Comment by lxgw** [comment]
https://github.com/lxgw/LxgwBright-Code

**Comment by rexzhang** [comment]
我在Joplin中试用了一下,感觉还不错
